development:
  adapter: postgresql
  encoding: utf8
  database: avto_net_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: avto_net_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: avto_net_production
  pool: 5
